### ISSUE TITLE
Fenaroli - Libro quinto ( Book Five ) [DONE. PENDING APPROVAL]

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#10]
Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each lesson in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
Hi @chrisdaaz ,
![image](https://user-images.githubusercontent.com/29619670/56148375-ca352580-5f6f-11e9-8596-51e53522f060.png)

The link for this doesn't work:
1) http://faculty-web.at.northwestern.edu/music/gjerdingen/partimenti/collections/Fenaroli/Book5/index.htm

2) Go into 'Gj1389'.

**Comment by chrisdaaz** [comment]
@chandrajason skip it. not sure that link ever worked.
