### ISSUE TITLE
Giovanni Furno

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#24]
http://faculty-web.at.northwestern.edu/music/gjerdingen/partimenti/collections/Furno/index.htm

Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each lesson in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
Also, Ive noticed that this has the same layout as  'Giancomo Insanguine #25'
where
the text is split into 2 columns - one in english and one in another language. how do I create the Markdown files for these? Should I only include the english translation?
If i were to include both translations, how do I 'split' or 'format' it such that it is split into 2?
Thanks, @chrisdaaz !
![image](https://user-images.githubusercontent.com/29619670/57590101-0320d580-74ef-11e9-83ad-9cbd6bd1ac66.png)

**Comment by chandrajason** [comment]
Similar issue on the question above -- this is the same problem as #12 
Fenaroli - Regole ( The Rules). Thanks :)

**Comment by chandrajason** [comment]
Reminder to myself: 
Copy the body part of the table via inspect element.
Paste it into the body section of the mark down file.
(The headings are the same)
