### ISSUE TITLE
Giancomo Insanguine

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#25]
http://faculty-web.at.northwestern.edu/music/gjerdingen/partimenti/collections/Insanguine/index.htm

Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each lesson in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
Reminder to myself:
Copy the body part of the table via inspect element.
Paste it into the body section of the mark down file.
(The headings are the same)
