### ISSUE TITLE
Durante - Regole (Rules)

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#3]
Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each topic in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
All is complete. @chrisdaaz , if you have double checked and everything is alright, then can you close this issue? I will start on a different issue later this week.
