### ISSUE TITLE
Durante - Partimenti numerati (Figured Basses)

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#4]
Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each topic in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
This is done - @chrisdaaz if you can review this and if it looks good then I can move on to another issue. Thanks!
