### ISSUE TITLE
Durante - Partimenti diminuiti (Embellished Basses) - Need to decide what to do with No. 100-103. (0-99 done.)

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#5]
Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each lesson in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
Messed up -- Closed the wrong one.
Was meant to close durante -regoles

**Comment by chandrajason** [comment]
@chrisdaaz 
![image](https://user-images.githubusercontent.com/29619670/58778774-728f5f80-8599-11e9-8a0a-2eaad60939a4.png)

What should we do for No.100- No. 103

**Comment by chrisdaaz** [comment]
are you asking about how to assign those pages a `weight`? for `no. 100` i gave it `weight = 2400` and it worked. it appears that `2400` hasn't been claimed, so, i think we can get away with using `2400` to `2403` for 100-103.

**Comment by chandrajason** [comment]
@chrisdaaz Noted.
I will do those now, thanks!

**Comment by chandrajason** [comment]
* note to self
GJ 100-103
has weights
2400-2403
