### ISSUE TITLE
Fenaroli - Libro terzo ( Book Three ) 

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/monuments#8]
Create markdown files following the instructions in the [wiki](https://github.com/nulib/monuments/wiki/Project-Notes) for each lesson in this section.

At the end of each work shift...
- Create a branch in GitHub Desktop
- Commit your files to your local repository
- Create a pull request for your most recent commits
- Add a comment to this issue that briefly describes the status of this work (e.g. "Stopped at 'Tied Basses').

### Done when
- Pull requests have been submitted and merged for every lesson in this section

**Comment by chandrajason** [comment]
@chrisdaaz Quick question - there is nothing here.
http://faculty-web.at.northwestern.edu/music/gjerdingen/partimenti/collections/Fenaroli/Book3/index.htm

^ what should I do about this issue, thanks!

**Comment by chrisdaaz** [comment]
you can skip it @jasonchandra thanks
